name: Build

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                java: [14]
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up JDK
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java }}
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - uses: actions/cache@v1
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
                ${{ runner.os }}-gradle-
        - name: Build with Gradle
          run: ./gradlew assemble
        - name: Check with Gradle
          run: ./gradlew check --info
